# Config file for automatic testing at travis-ci.com

language: python
python:
  - "3.7"

# Command to install dependencies, e.g. pip install -r requirements_dev.txt --use-mirrors
install:
    - pip install -r requirements_dev.txt
    - pip install pytest-cov codecov

# Command to run tests, e.g. python setup.py test
script:
    - pytest --cov=generic_search tests
after_success:
    - codecov


